[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key="PageUp"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key="PageDown"
